---
  - name: "add repo"
    apt_repository:
      repo="ppa:ondrej/php"
      update_cache=yes

  - name: install packages
    apt: pkg={{ item }} update_cache=yes state=latest
    php_version: "7.1"
    with_items:
      - git
      - mcrypt
      - nginx
      - php7.1-common
      - php7.1-cli
      - php7.1-curl
      - php7.1-fpm
      - php7.1-intl
      - php7.1-json
      - php7.1-mcrypt
      - php7.1-sqlite3
      - php7.1-mbstring
      - php7.1-imap
      - php7.1-dev
      - php7.1-xml
      - sqlite3
  - name: ensure php7.1-fpm cgi.fix_pathinfo=0
    lineinfile: dest=/etc/php/7.1/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
    notify:
      - restart php7.1-fpm
      - restart nginx
  - name: enable php7.1 mcrypt module
    shell: php7.0enmod mcrypt
    args:
      creates: /etc/php/7.1/cli/conf.d/20-mcrypt.ini
  - name: create /var/www/ directory
    sudo: yes
    sudo_user: dxccnaadmin
    file: dest=/var/www/ state=directory owner=www-data group=www-data mode=0700

  - name: Clone git repository
    git: >
      dest=/var/www/laravel
      repo=https://github.com/laravel/laravel.git
      update=no
    sudo: yes
    sudo_user: dxccnadmin 
    register: cloned
  - name: install composer
    shell: curl -sS https://getcomposer.org/installer |php  -- --install-dir=/usr/local/bin --filename=composer
    args:
      creates: /usr/local/bin/composer

  - name: composer create-project
    composer: command=create-project working_dir=/var/www/laravel optimize_autoloader=no
    sudo: yes
    sudo_user: dxccnaadmin
    when: cloned|changed
  - name: set APP_DEBUG=false
    lineinfile: dest=/var/www/laravel/.env.example regexp='^APP_DEBUG=' line=APP_DEBUG=false

  - name: set APP_ENV=production
    lineinfile: dest=/var/www/laravel/.env.example regexp='^APP_ENV=' line=APP_ENV=production
  - name: Configure nginx
    template: src=nginx.conf dest=/etc/nginx/sites-available/default
    notify:
      - restart php7.1-fpm
      - restart nginx
  - name: change the permission
    become: yes
    shell: chmod -R 777 /var/www/laravel 
